package cn.et.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sage
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    private String sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ssex
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sid
     *
     * @return the value of student.sid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sid
     *
     * @param sid the value for student.sid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gid
     *
     * @return the value of student.gid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gid
     *
     * @param gid the value for student.gid
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sage
     *
     * @return the value of student.sage
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public String getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sage
     *
     * @param sage the value for student.sage
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public void setSage(String sage) {
        this.sage = sage == null ? null : sage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ssex
     *
     * @return the value of student.ssex
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ssex
     *
     * @param ssex the value for student.ssex
     *
     * @mbg.generated Fri Mar 15 17:30:38 CST 2019
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}